### ISSUE TITLE
需求：刷流插件增加 针对站点的全局H&R配置项

### ISSUE THREAD

**Issue by MDCY9008** [InfinityPacer/MoviePilot-Plugins-PR#15]
对于```学校```等全站H&R站点，按照目前的处理逻辑，站点没有HR标签，导致没有正常的识别出是H&R种子，故无法按照H&R逻辑正确删种，可否增加```针对站点的全局H&R配置项```

**Comment by MDCY9008** [comment]
个人拙见，在这里加一项or的判断值应该可以实现，本人学艺不精，请大佬评估，顺带想问一下，有规划更加丰富的删种规则吗，目前的逻辑是顺序判断，只要有一个条件符合就删种，相当于```或```的逻辑了，希望能支持```与```的逻辑。
最后，感谢大佬对刷流插件的完善。
![image](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/54255527/6f48666c-ed7d-4eb4-9117-d539584f3758)

**Comment by InfinityPacer** [comment]
@MDCY9008 需要在添加种子时标记HR种子，这个需求已经添加到开发计划了，这几天应该会跟删种汇报一起更新。此外，与逻辑受限与插件的交互限制，短期内应该暂无计划，看后续MP主程序的动态交互方案如何改造再进一步评估。
